#!/bin/bash

# init main script
if [ -f "$HOME/bin/init" ]
then
	source "$HOME/bin/init"
fi

current_path=$(pwd)
dest=.last_version.tar.gz
tmp_folder=.last_version

# init site config - from module path
if [ -f "$(pwd)/../../../.env" ]
then
	source "$(pwd)/../../../.env"
fi

# clear old version
if [ -d "$tmp_folder" ]
then
	rm -R "$tmp_folder"
fi
if [ -f "$dest" ]
then
	rm "$dest"
fi

# make full copy
mkdir "$tmp_folder"
for f in $(find | grep -v ".dev" | grep -v ".git" | grep -v "screenshots" | grep -v "bin")
do
	if [ -f "$f" ]
	then
		cp --parents "$f" "$tmp_folder"
	fi
done

# convert lang files to windows-1251
for f in $(find "$tmp_folder" | grep /lang/ | grep .php)
do
	iconv -f UTF-8 -t WINDOWS-1251 -c "$f" > tmp
	mv -f tmp "$f"
done

tar -zcvf "$dest" "$tmp_folder"
